### ISSUE TITLE
Closures Quiz - wrong answer is showing as a right one

### ISSUE THREAD

**Issue by petardotjs** [codeguage-code/exercises#1]
Hello, I'd like to report an issue with the Closures Quiz on your website. The last task is showing a wrong answer as a right one. I thought it could be a bug, but even the explanation to it was wrong so that was definitely not the case.

```
var a = 1;

function f1() {
    var b = 2;
    function f2() { console.log(a, b); }

    return f2;
}

var f2 = f1();
var b = 3;

function f3() {
    a = 5;
    f2();
}

f3();
```

The following code prints 5 2, not 1 2. Please, fix that and rewrite the explanation to it.

**Comment by codeguage-code** [comment]
@petardotjs we are extremely sorry for the inconvenience.
Thanks for pointing out this issue. 

The first problem is that `a = 5` should've been `var a = 5`, and secondly there should've been a slight change in the explanation.

**Comment by codeguage-code** [comment]
The issue has been rectified and you can now see the correct explanation. 🙂
